name: "Format code"

# run on pull requests to develop
on:
  pull_request:
    branches:
      - develop-pros-4

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # check out HEAD on the branch
          ref: ${{ github.head_ref }}
          # make sure the parent commit is grabbed as well, because
          # that's what will get formatted (i.e. the most recent commit)
          fetch-depth: 2
      # format the latest commit
      - uses: purduesigbots/clang-format-action@9fc0a34df41572eb6f168d3e45f2338d9e447892
        # use one of clang-format's supported styles or leave this out to use the style in your .clang-format file
      # commit the changes (if there are any)
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_message: "style: 🎨 apply clang-format changes"
          branch: ${{ github.head_ref }}
